### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by kaspars-ozols** [Geta/product-filter#1]
![image](https://cloud.githubusercontent.com/assets/6103815/18944278/362434e4-862d-11e6-99ca-c7f344b1a5f5.png)

https://geta.github.io/product-filter/

**Comment by hkvalvik** [comment]
Should be working again now

**Comment by kaspars-ozols** [comment]
![image](https://cloud.githubusercontent.com/assets/6103815/19113128/f1fe0054-8b10-11e6-91a6-2051c6bd3039.png)

There still seems to be problem with prices

**Comment by hkvalvik** [comment]
Removed the prices for now, in most projects they should be displayed as a range slider.
That's right, the demo is a bit limited since it's just using static json instead of a real api.
Updated the demo with a better explanation of why the filtering doesn't actually work.
